create table if not exists public.export_items (
  id bigint generated by default as identity primary key,
  sector text not null,
  sheet_name text not null,
  name text not null,
  importance integer not null default 0 check (importance >= 0 and importance <= 5),
  description text,
  related_stocks text,
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint export_items_sheet_name_key unique (sheet_name)
);

create table if not exists public.export_data (
  id bigint generated by default as identity primary key,
  sheet_name text not null,
  period text not null check (period ~ '^[0-9]{4}-[0-9]{2}$'),
  sector text,
  description text,
  importance numeric,
  yoy numeric,
  mom numeric,
  daily_avg numeric,
  as_of_date date,
  is_partial boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.export_items
  add column if not exists description text,
  add column if not exists related_stocks text,
  add column if not exists note text,
  add column if not exists is_active boolean not null default true;

alter table public.export_data
  add column if not exists sheet_name text,
  add column if not exists period text,
  add column if not exists sector text,
  add column if not exists description text,
  add column if not exists importance numeric,
  add column if not exists daily_avg numeric,
  add column if not exists as_of_date date,
  add column if not exists is_partial boolean not null default false;

create index if not exists export_items_sector_idx
  on public.export_items (sector);

create index if not exists export_items_is_active_idx
  on public.export_items (is_active);

create unique index if not exists export_data_sheet_name_period_unique_idx
  on public.export_data (sheet_name, period);
