create table if not exists public.export_items (
  id bigint generated by default as identity primary key,
  sector text not null,
  sheet_name text not null,
  name text not null,
  importance integer not null default 0 check (importance >= 0 and importance <= 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint export_items_sheet_name_key unique (sheet_name)
);

create table if not exists public.export_data (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.export_items(id) on delete cascade,
  ym text not null check (ym ~ '^[0-9]{4}-[0-9]{2}$'),
  avg_export numeric,
  yoy numeric,
  mom numeric,
  price_yoy numeric,
  qoq numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint export_data_item_id_ym_key unique (item_id, ym)
);

create index if not exists export_items_sector_idx
  on public.export_items (sector);

create index if not exists export_data_item_id_ym_idx
  on public.export_data (item_id, ym);
