create table if not exists public.market_finviz_watchlist (
  id bigint generated by default as identity primary key,
  ticker text not null,
  sector text not null,
  display_name text not null,
  keywords text,
  star integer not null default 0 check (star >= 0 and star <= 3),
  chart_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_finviz_watchlist_ticker_key unique (ticker)
);

alter table public.market_finviz_watchlist
  add column if not exists ticker text,
  add column if not exists sector text,
  add column if not exists display_name text,
  add column if not exists keywords text,
  add column if not exists star integer not null default 0 check (star >= 0 and star <= 3),
  add column if not exists chart_url text,
  add column if not exists sort_order integer not null default 0,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'market_finviz_watchlist_ticker_key'
  ) then
    alter table public.market_finviz_watchlist
      add constraint market_finviz_watchlist_ticker_key unique (ticker);
  end if;
end $$;

create index if not exists market_finviz_watchlist_sector_idx
  on public.market_finviz_watchlist (sector);

create index if not exists market_finviz_watchlist_is_active_idx
  on public.market_finviz_watchlist (is_active);

create index if not exists market_finviz_watchlist_sort_order_idx
  on public.market_finviz_watchlist (sort_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'market_finviz_watchlist_set_updated_at'
  ) then
    create trigger market_finviz_watchlist_set_updated_at
      before update on public.market_finviz_watchlist
      for each row
      execute function public.set_updated_at();
  end if;
end $$;

alter table public.market_finviz_watchlist enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'market_finviz_watchlist'
      and policyname = 'market_finviz_watchlist_public_select'
  ) then
    create policy market_finviz_watchlist_public_select
      on public.market_finviz_watchlist
      for select
      to anon, authenticated
      using (true);
  end if;
end $$;
